name: Java CI with Maven

on:
  push:
 
    
  pull_request:
 
     
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up ChromeDriver
      uses: nanasess/setup-chromedriver@v2
      with:
        chromedriver-version: 'latest'

    - name: Set up Xvfb
      run: |
        export DISPLAY=:99
        sudo Xvfb :99 -ac -screen 0 1280x1024x24 > /dev/null 2>&1 &
        
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

 

    - name: Run Selenium tests
      run: mvn clean test

    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: target/surefire-reports

    - name: Send notifications
      if: failure()
      run: echo "Test failures occurred. Please check the test reports for details."
