
name: Java CI with Maven

on:
  - pull_request
  - push
  - workflow_dispatch
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
   
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run Selenium tests
      run: mvn test
    # Step to capture test results as artifacts
    - name: Archive test results
      if: always()  # Ensure this step runs even if the previous steps fail
      uses: actions/upload-artifact@v2
      with:
          name: test-results
          path: tests_output 
    - name: Send notifications
      if: failure() 
      run: |
          
          echo "Test failures occurred. Please check the test reports for details."
   
