name: Selenium Tests

on:
  push:

  pull_request:
  workflow_dispatch:
  

jobs:
  selenium_tests_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Install Google Chrome
      run: |
        sudo apt update
        sudo apt install -y google-chrome-stable

    - name: Install ChromeDriver
      uses: nanasess/setup-chromedriver@v2
      with:
        version: latest

    - name: Run Selenium tests
      run: mvn clean test
